name: env
channels:
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.2.0
  - adwaita-icon-theme=48.0
  - affine=2.4.0
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.9
  - aiosignal=1.3.1
  - alabaster=1.0.0
  - alembic=1.15.2
  - alsa-lib=1.2.13
  - anyio=4.6.2.post1
  - aom=3.9.1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=24.2.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - binutils_impl_linux-64=2.43
  - binutils_linux-64=2.43
  - bleach=6.2.0
  - blosc=1.21.6
  - bokeh=3.6.1
  - boto3=1.35.63
  - botocore=1.35.63
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.6.15
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.0
  - cairo=1.18.4
  - cdsapi=0.7.5
  - certifi=2025.6.15
  - cf_xarray=0.10.0
  - cffi=1.17.1
  - cfgrib=0.9.15.0
  - cftime=1.6.4
  - charset-normalizer=3.4.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.1.0
  - cmdstan=2.35.0
  - cmdstanpy=1.2.5
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - contextily=1.6.2
  - contourpy=1.3.1
  - convertdate=2.4.0
  - cpython=3.12.10
  - cryptography=43.0.3
  - cuda=12.8.1
  - cuda-cccl_linux-64=12.8.90
  - cuda-command-line-tools=12.8.1
  - cuda-compiler=12.8.1
  - cuda-crt-dev_linux-64=12.8.93
  - cuda-crt-tools=12.8.93
  - cuda-cudart=12.8.90
  - cuda-cudart-dev=12.8.90
  - cuda-cudart-dev_linux-64=12.8.90
  - cuda-cudart-static=12.8.90
  - cuda-cudart-static_linux-64=12.8.90
  - cuda-cudart_linux-64=12.8.90
  - cuda-cuobjdump=12.8.90
  - cuda-cupti=12.8.90
  - cuda-cupti-dev=12.8.90
  - cuda-cuxxfilt=12.8.90
  - cuda-driver-dev=12.8.90
  - cuda-driver-dev_linux-64=12.8.90
  - cuda-gdb=12.8.90
  - cuda-libraries=12.8.1
  - cuda-libraries-dev=12.8.1
  - cuda-nsight=12.8.90
  - cuda-nvcc=12.8.93
  - cuda-nvcc-dev_linux-64=12.8.93
  - cuda-nvcc-impl=12.8.93
  - cuda-nvcc-tools=12.8.93
  - cuda-nvcc_linux-64=12.8.93
  - cuda-nvdisasm=12.8.90
  - cuda-nvml-dev=12.8.90
  - cuda-nvprof=12.8.90
  - cuda-nvprune=12.8.90
  - cuda-nvrtc=12.8.93
  - cuda-nvrtc-dev=12.8.93
  - cuda-nvtx=12.8.90
  - cuda-nvvm-dev_linux-64=12.8.93
  - cuda-nvvm-impl=12.8.93
  - cuda-nvvm-tools=12.8.93
  - cuda-nvvp=12.8.93
  - cuda-opencl=12.8.90
  - cuda-opencl-dev=12.8.90
  - cuda-profiler-api=12.8.90
  - cuda-runtime=12.8.1
  - cuda-sanitizer-api=12.8.93
  - cuda-toolkit=12.8.1
  - cuda-tools=12.8.1
  - cuda-version=12.8
  - cuda-visual-tools=12.8.1
  - cudnn=9.8.0.87
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - cytoolz=1.0.0
  - dask=2024.11.2
  - dask-core=2024.11.2
  - dask-expr=1.1.19
  - datapi=0.2.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.9
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecat=2.1.3
  - distributed=2024.11.2
  - docutils=0.21.2
  - earthengine-api=1.4.2
  - eccodes=2.39.0
  - entrypoints=0.4
  - epoxy=1.5.10
  - esmf=8.7.0
  - esmpy=8.7.0
  - et_xmlfile=2.0.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - filelock=3.18.0
  - findlibs=0.0.5
  - fiona=1.10.1
  - flatbuffers=24.12.23
  - folium=0.19.5
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gast=0.6.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gdal=3.10.2
  - gdk-pixbuf=2.42.12
  - gds-tools=1.13.1.3
  - geoalchemy2=0.16.0
  - geographiclib=2.0
  - geopandas=1.0.1
  - geopandas-base=1.0.1
  - geopy=2.4.1
  - geos=3.13.0
  - geotiff=1.7.3
  - gflags=2.2.2
  - giflib=5.2.2
  - glib-tools=2.82.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-api-core=2.22.0
  - google-api-python-client=2.154.0
  - google-auth=2.36.0
  - google-auth-httplib2=0.2.0
  - google-cloud-core=2.4.1
  - google-cloud-storage=2.19.0
  - google-crc32c=1.1.2
  - google-pasta=0.2.0
  - google-resumable-media=2.7.2
  - googleapis-common-protos=1.66.0
  - graphite2=1.3.13
  - graphviz=12.2.1
  - greenlet=3.1.1
  - grpcio=1.67.1
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=10.4.0
  - hdf4=4.2.15
  - hdf5=1.14.4
  - hicolor-icon-theme=0.17
  - holidays=0.71
  - hpack=4.0.0
  - httpcore=1.0.7
  - httplib2=0.22.0
  - httpx=0.28.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.5
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jasper=4.2.5
  - jedi=0.19.2
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - json-c=0.18
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keras=3.9.0
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=12.8.4.1
  - libcublas-dev=12.8.4.1
  - libcudss=0.5.0.16
  - libcufft=11.3.3.83
  - libcufft-dev=11.3.3.83
  - libcufile=1.13.1.3
  - libcufile-dev=1.13.1.3
  - libcups=2.3.3
  - libcurand=10.3.9.90
  - libcurand-dev=10.3.9.90
  - libcurl=8.12.1
  - libcusolver=11.7.3.90
  - libcusolver-dev=11.7.3.90
  - libcusparse=12.5.8.93
  - libcusparse-dev=12.5.8.93
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgdal-core=3.10.2
  - libgdal-grib=3.10.2
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglu=9.0.3
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgrpc=1.67.1
  - libheif=1.19.5
  - libhwloc=2.11.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - libllvm14=14.0.6
  - libllvm20=20.1.0.rc1
  - liblzma=5.6.4
  - libmagma=2.8.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnpp=12.3.3.100
  - libnpp-dev=12.3.3.100
  - libnsl=2.0.1
  - libntlm=1.4
  - libnvfatbin=12.8.90
  - libnvfatbin-dev=12.8.90
  - libnvjitlink=12.8.93
  - libnvjitlink-dev=12.8.93
  - libnvjpeg=12.3.5.92
  - libnvjpeg-dev=12.3.5.92
  - libopenblas=0.3.28
  - libopengl=1.7.0
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.1
  - libprotobuf=5.28.3
  - libre2-11=2024.07.02
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsanitizer=13.3.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.48.0
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=14.2.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libutf8proc=2.9.0
  - libuuid=2.38.1
  - libuv=1.50.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=3.0.0
  - libxkbcommon=1.8.0
  - libxkbfile=1.1.0
  - libxml2=2.13.5
  - libzip=1.11.2
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - lightning-utilities=0.14.3
  - llvm-openmp=20.1.3
  - llvmlite=0.43.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.10.0
  - lzo=2.10
  - make=4.4.1
  - mako=1.3.10
  - mapclassify=2.8.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mercantile=1.2.1
  - minizip=4.0.7
  - mistune=3.0.2
  - mkl=2024.2.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - msgpack-python=1.1.0
  - multidict=6.1.0
  - multiurl=0.3.3
  - munkres=1.1.4
  - namex=0.0.8
  - nbclient=0.10.1
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nccl=2.26.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf-fortran=4.6.1
  - netcdf4=1.7.2
  - networkx=3.4.2
  - notebook-shim=0.2.4
  - nsight-compute=2025.1.1.2
  - nspr=4.36
  - nss=3.108
  - numba=0.60.0
  - numpy=2.0.0
  - ocl-icd=2.3.3
  - opencl-headers=2024.10.24
  - openjpeg=2.5.2
  - openldap=2.6.8
  - openpyxl=3.1.5
  - openssl=3.5.0
  - opt_einsum=3.4.0
  - optree=0.15.0
  - optuna=4.2.1
  - orc=2.0.3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.56.2
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - pluggy=1.5.0
  - proj=9.5.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - propcache=0.2.1
  - prophet=1.1.6
  - proto-plus=1.25.0
  - protobuf=5.28.3
  - psutil=6.1.0
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.0.0
  - pyaml=25.5.0
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.1
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pydot=4.0.0
  - pygments=2.18.0
  - pymeeus=0.5.12
  - pyogrio=0.10.0
  - pyopenssl=24.2.1
  - pyparsing=3.2.0
  - pyproj=3.7.0
  - pysocks=1.7.1
  - pytest=8.3.3
  - pytest-runner=6.0.0
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-eccodes=2.37.0
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.12
  - pytorch=2.6.0
  - pytorch-lightning=2.5.1
  - pytz=2024.1
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.6.6
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rioxarray=0.17.0
  - rpds-py=0.21.0
  - rsa=4.9
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.5.10
  - s3transfer=0.10.3
  - scikeras=0.13.0
  - scikit-learn=1.6.1
  - scikit-optimize=0.10.2
  - scipy=1.15.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.5.0
  - setuptools-scm=8.1.0
  - setuptools_scm=8.1.0
  - shap=0.47.2
  - shapely=2.0.6
  - six=1.16.0
  - sleef=3.8
  - slicer=0.0.8
  - snappy=1.2.1
  - sniffio=1.3.1
  - snowballstemmer=2.2.0
  - snuggs=1.4.7
  - sodapy=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sparse=0.15.5
  - sphinx=8.1.3
  - sphinx-click=6.0.0
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - sqlalchemy=1.4.49
  - sqlite=3.48.0
  - stack_data=0.6.2
  - stanio=0.5.1
  - statsmodels=0.14.4
  - svt-av1=2.3.0
  - sympy=1.13.3
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tbb-devel=2021.13.0
  - tblib=3.0.0
  - tenacity=9.0.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - tensorflow-gpu=2.18.0
  - termcolor=2.5.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.1.0
  - toolz=1.0.0
  - torchmetrics=1.7.1
  - tornado=6.4.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - triton=3.2.0
  - types-python-dateutil=2.9.0.20241003
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - uritemplate=4.1.1
  - urllib3=2.2.3
  - wayland=1.23.1
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.0
  - widgetsnbextension=4.0.13
  - wrapt=1.16.0
  - x265=3.5
  - xarray=2025.1.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xesmf=0.8.8
  - xgboost=3.0.0
  - xkeyboard-config=2.43
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.18.3
  - zeromq=4.3.5
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - astroid==3.3.8
      - coverage==7.6.10
      - datacube==1.9.0rc11.dev1+g1df7cd99
      - dill==0.3.9
      - hypothesis==6.123.17
      - isort==5.13.2
      - moto==4.2.14
      - pycodestyle==2.12.1
      - pylint==3.3.3
      - pytest-cov==6.0.0
      - pytest-httpserver==1.1.0
      - pytest-timeout==2.3.1
      - responses==0.25.6
      - tomlkit==0.13.2
      - xmltodict==0.14.2
